import logo from '../assets/logo.png'

const menubList=[
    {
        logo:"f",
        name:"Home",
        link:''
    },
    {
        logo:"f",
        name:"Profile",
        link:'/profile'
    },
    {
        logo:"f",
        name:"Post",
        link:'/Post'
    },
    {
        logo:"f",
        name:"Bookmark",
        link:'/bookmark'
    },
    {
        logo:"f",
        name:"Log-out",
        link:'/sign-out'
    }
]

const following=[
    {
        logo:{logo},
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    }
]

const posts=[
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    }
]

export {menubList,following,posts}