import logo from '../assets/logo.png'

const menubList=[
    {
        logo:"f",
        name:"Home"
    },
    {
        logo:"f",
        name:"Profile"
    },
    {
        logo:"f",
        name:"Following"
    },
    {
        logo:"f",
        name:"Bookmark"
    },
    {
        logo:"f",
        name:"Settings"
    }
]

const following=[
    {
        logo:{logo},
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    },
    {
        logo:logo,
        name:"Home",
        email:"chsffvfv@gmail.com"
    }
]

const posts=[
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    },
    {
        user:{
        img:logo,
        name:"chandraKumar",
        email:"chanwsff@gmail.com"
        },
        content:"gggfgfgfgdfggfgtgthtgffffffffffffffffffffffffdbbbbbbbbbbbbdddddddd"
    }
]

export {menubList,following,posts}